// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package main

import (
	kratos "github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	"example.com/kratos-fixture/internal/biz"
	"example.com/kratos-fixture/internal/conf"
	"example.com/kratos-fixture/internal/data"
	"example.com/kratos-fixture/internal/server"
	"example.com/kratos-fixture/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
// 合规：生成头「Code generated by Wire. DO NOT EDIT.」完整 → generated_code_edit pass
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(greeterService, logger)
	httpServer := server.NewHTTPServer(greeterService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
